{
    "engines": {
        "csslint": {
            "enabled": true
        },
        "fixme": {
            "enabled": true
        },
        "duplication": {
            "enabled": true,
            "config": {
                "languages": [
                    "javascript"
                ]
            },
            "exclude_paths": [
                "test/"
            ]
        }
    },
    "ratings": {
        "paths": [
            "**.css",
            "**.js",
            "**.jsx"
        ]
    },
    "exclude_paths": []
}
